spring.application.name=RR

server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:mariadb://localhost:3307/rr
spring.datasource.username=RR
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
# spring.jpa.show-sql=true


# Hibernate SQL ?? ?? = ???? ?? 3? ??? ?? ture ???
spring.jpa.show-sql=false

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF


# ============================
# ? JWT ??
# ============================

# ?? 32??? ??! (??? ??? ?? ????? ??? ?)
jwt.secret=f0510aef6450b0edbf4c03cd9570bceec6976782b9d7dacc633e568706e3c054

# Access Token ???? (ms) 30? : 1800000
jwt.access-exp-ms=1800000

# Refresh Token ???? (ms) 14?
jwt.refresh-exp-ms=1209600000

spring.session.store-type=none
